version: "3.8"

services:
  app:
    build: .
    container_name: goit-cs-hw-06-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: goit-cs-hw-06-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
